spring.application.name=helix-chatbot

spring.output.ansi.enabled=ALWAYS

server.port=8096

helix.login.username=ChatAPI
helix.login.password=Bbv4ch4t4pi2026$
helix.api.url=https://bbvaperu-dev-restapi.onbmc.com

spring.ai.google.genai.api-key=KEY_GEMINI
#spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.chat.options.model=gemini-3.1-flash-lite
